### ISSUE TITLE
Alpha Sorting for custom generic mapper

### ISSUE THREAD

**Issue by achmed13** [oleg-shilo/codemap.vscode#50] opened 2020-12-16 17:42 UTC
I have set up a custom mapper for MapBasic (syntax similar to VBScript) as follows:

    "codemap.mb": [
        {
            "pattern": "^([Ff]unction|[Ss]ub) .*",
            "clear": "[Ff]unction |[Ss]ub ",
            "suffix": "",
            "icon": "function"
        }
    ],
    "codemap.sortingEnabled": true,

It is correctly listing my Functions and Subs, but they are sorted by position and not by name. I have enabled Codemap: Sorting Enabled in the settings, as reflected in the above snippet from settings.json.

Do I need to do something else to enable alphabetical sorting?

Thanks!

**Comment by oleg-shilo** [comment] 2020-12-17 12:56
I don't think so.

Can you please share a MapBasic code so I can try to debug?

**Comment by achmed13** [comment] 2020-12-17 16:20
Here is a simple script, zipped. The extension is .mb, and the syntax is similar to VB. The apostrophe is the comment character.

Thanks for taking a look.

[ScaleRuler.zip](https://github.com/oleg-shilo/codemap.vscode/files/5710741/ScaleRuler.zip)

**Comment by achmed13** [comment] 2021-01-25 20:48
I believe I have found the problem. In mapper_generic.js it is creating the "members" array, but it never sorts it. I added a sort on line 58 (before members.forEach) and it seems to be sorting fine now. It does not obey the extension preference Codemap: Sorting Enabled, but for my purposes I always sort alphabetically anyhow. 

Thanks for the great extension!

**Comment by oleg-shilo** [comment] 2021-05-14 14:56
The actual problem was caused by the very root level not being sorted. 
Unfortunately the approach you have proposed conflicts with the nested items and only works for the flat trees like in your sample.

The problem is fixed now (directly). The fix will be available in the very next release.

**Closed** 2022-11-11 12:38 UTC
Labels: bug, Done
